const manageData = [
  {
    id: "1",
    name: "Пулатов Шухрат Абдужаббарович",
    role: "Хоким Мирабадского района",
    email: "mirobod@tashkent.uz",
    phone: "(71) 233–29–86, (71) 255–86–85",
    workDays: "Вторник и четверг с 16:00 до 19:00",
    imgUrl: "https://i.ibb.co/nDS1f2t/heads.png",
  },
  {
    id: "2",
    name: "Салайдинов Ашраф Ғойибназарович",
    role: "Туман ҳокимининг 1-ўринбосари",
    email: "mirobod@tashkent.uz",
    phone: "(71) 233–29–86, (71) 255–86–85",
    workDays: "Вторник и четверг с 16:00 до 19:00",
    imgUrl: "https://i.ibb.co/kMDhjxB/heads1.png",
  },
  {
    id: "3",
    name: "Нажмиддинов Фарход Нажмиддинович",
    role: "Туман ҳокимининг ўринбосари",
    email: "mirobod@tashkent.uz",
    phone: "(71) 233–29–86, (71) 255–86–85",
    workDays: "Вторник и четверг с 16:00 до 19:00",
    imgUrl: "https://i.ibb.co/kMDhjxB/heads1.png",
  },
  {
    id: "4",
    name: "Саидов Санжархон Асрорович",
    role: "Туман ҳокимининг ўринбосари",
    email: "mirobod@tashkent.uz",
    phone: "(71) 233–29–86, (71) 255–86–85",
    workDays: "Вторник и четверг с 16:00 до 19:00",
    imgUrl: "https://i.ibb.co/kMDhjxB/heads1.png",
  },
  {
    id: "5",
    name: "Шукуров Тулаган Рустамович",
    role: "Бўлим бошлиғи - туман ҳокимининг ўринбосари",
    email: "mirobod@tashkent.uz",
    phone: "(71) 233–29–86, (71) 255–86–85",
    workDays: "Вторник и четверг с 16:00 до 19:00",
    imgUrl: "https://i.ibb.co/kMDhjxB/heads1.png",
  },
  {
    id: "6",
    name: "Мадаминова Феруза Воҳидовна",
    role: "Бўлим бошлиғи - туман ҳокимининг ўринбосари",
    email: "mirobod@tashkent.uz",
    phone: "(71) 233–29–86, (71) 255–86–85",
    workDays: "Вторник и четверг с 16:00 до 19:00",
    imgUrl: "https://i.ibb.co/kMDhjxB/heads1.png",
  },
  {
    id: "7",
    name: "Саидханов Саидрасул Мансурович",
    role: "Ташкилий-кадрлар гурухи рахбари",
    email: "mirobod@tashkent.uz",
    phone: "(71) 233–29–86, (71) 255–86–85",
    workDays: "Вторник и четверг с 16:00 до 19:00",
    imgUrl: "https://i.ibb.co/wy30n8N/heads3.png",
  },
];

export default manageData;
